version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - target/SpringWebAwsCodePipelineApplication.jar
  discard-paths: yes
